### ISSUE TITLE
mc takes forever to open

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/Rigbox#10]
cc @k1o0 

Certain operations like choosing a new mouse also. Need to do some profiling to figure out what is slow and brainstorm ways to speed it up.

**Comment by k1o0** [comment]
Hopefully this is in part solved by https://github.com/cortex-lab/Rigbox/pull/119

To do:
- [ ] Run new profiler on mc startup
- [ ] Write performance test for mc
