### ISSUE TITLE
Zrig4 not posting water to alyx

### ISSUE THREAD

**Issue by laurax452** [cortex-lab/Rigbox#101]
Zrig 4 is not posting water to Alyx, MC shows mouse not getting water even though reward has been given during trial. Originally thought to be an issue for LEW014, but PC038 was just run on this rig and had same issue. Performance has massively dropped for a trained animal in this rig (LEW014) so if someone could also check the history logs this would be useful too, in case the cause behind this issue would also affect the task. (Nothing obviously wrong during training)
Thanks

**Comment by k1o0** [comment]
@jaib1 Could you copy/paste the command history for this rig?  There should be a warning about posting to Alyx somewhere.
