### ISSUE TITLE
condition numbers

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/Rigbox#12]
Would be great for a Parameters object to have a special field "condition number" that just counts 1:n for however many conditional parameters there are, then writes the appropriate number into block.trials.cond. 

It could also display this in the conditional panel, but it would have to be a read-only field.

**Comment by nsteinme** [comment]
Useful for mimicking certain useful features of mpep: https://github.com/cortex-lab/Rigbox/issues/13

**Comment by k1o0** [comment]
Although this has been a feature for years, it's undocumented.  To do:

- [ ] Document solutions to issues #13 & #12 on Wiki and instructions. 
- [ ] Add randomiseConditions parameter to default parameters or maybe create special checkbox above conditions table?

**Comment by k1o0** [comment]
Wiki updated, closing this.
