### ISSUE TITLE
Add Rigbox config files

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/Rigbox#127]
Related to #123.  The following configuration files would be helpful to users who wish to set up Rigbox from scratch: 

- [x] configure Timeline
- [x] configure Window
- [x] configure sockets
- [x] configure services
- [x] configure paths
- [x] configure hardware inputs and outputs
- [x] configure audio devices
- [x] configure Alyx (the client)

These could be placed in doc/setup/ and be developed on a new branch that's merged into dev each time a new config file is created.

Pros to this approach:
1. It helps users configure their objects the 'right' way using validation methods to add parameters e.g. srv.StimulusControl/create, hw.DaqRotaryEncoder/wiringInfo, hw.Timeline/wiringInfo, hw.Timeline/addInput
2. Demonstrates features that not many users know about, for instance adding timeline and path override parameters to their hardware files, how services can be configured for various applications.
3. Scripts are more useful than other types of documentation as they can request user input and help users setup thing whilst at the same time acting as a tutorial through demonstration.
4. We could do away with example binary files such as the hardware and remote MAT files, which aren't easy to track in GitHub.

**Comment by jaib1** [comment]
should we also include docs on calibrations? e.g. how to perform gamma and reward valve calibrations?

**Comment by k1o0** [comment]
These should be in readthedocs.io

**Comment by k1o0** [comment]
Done in v2.3
