### ISSUE TITLE
Implement full string support for parameters

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/Rigbox#134]
Strings were for some reason strictly forbidden (I don't think tables supported them when the ParamEditor was first written), so strings were converted to cellstrings instead.  I partially added string support in Parameters:
https://github.com/cortex-lab/Rigbox/blob/8820651acb28309b952f4581aeeba684f184d0b5/%2Bexp/Parameters.m#L140-L144
... and support for conditional char arrays:
https://github.com/cortex-lab/Rigbox/blob/8820651acb28309b952f4581aeeba684f184d0b5/%2Bexp/Parameters.m#L73-L76

However this still exists in the ParamEditor:
https://github.com/cortex-lab/Rigbox/blob/8820651acb28309b952f4581aeeba684f184d0b5/%2Beui/ParamEditor.m#L344-L345

I don't see why strings can't be fully supported now, but we should write some tests to make sure they're treated correctly by the ParamEditor and Parameters objects.  More broadly, the Rigbox code always uses cellstrings for processing lists of strings and I've been meaning to test the performance of string array manipulations to see if they're fast.  They're certainly more intuitive to work with than cell arrays, however that may not be reflected in the performance.  Counter intuitively for something that carries mixed data types, cell array manipulations are sometimes much faster than the same manipulation to other array types.

_Originally posted by @k1o0 in https://github.com/cortex-lab/Rigbox/pull/133#issuecomment-477182423_

**Comment by jaib1** [comment]
#146 done
