### ISSUE TITLE
Hardware JSON files are large

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/Rigbox#168]
For some rigs the hardware info file is in the MB range.  The issue may be precision being too high, e.g. in the water calibration table:
```
{"durationSecs":0.15,"volumeMicroLitres":4.6555555555555541}
```
As this only happens on some rigs it may be a version issue as older versions of MATLAB use the JSONlab toolbox:
https://github.com/cortex-lab/Rigbox/blob/c98a2477e37fd68a62f3a98988b93d6ba1e61640/cb-tools/obj2json.m#L4-L7

@jaib1 mind looking into the rig versions and ideally provide some example experiment references?

**Comment by jaib1** [comment]
```
The issue may be precision being too high, e.g. in the water calibration table:
```

If this is the case, could change hw.WeighingScale to round down
