### ISSUE TITLE
quick view for logging weekend hydrogel

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/Rigbox#19]
@k1o0

**Comment by nsteinme** [comment]
@k1o0 @laurax452 Miles, Laura, could you discuss together what the optimal form of this should be, what it should look like? If we have a clear picture of that before tomorrow (Wed) at noon, then we can bring it up as a task in the "superusers" meeting and see who can work on it, if not Miles.

**Comment by k1o0** [comment]
This was resolved by Peter
