### ISSUE TITLE
Standardize error identifiers

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/Rigbox#193]
We should probably standardize the identifiers we use as this may be useful when we finally improve error handling in SignalsExp.  Below are some suggestions:

0. Standard format for identifiers? Maybe `module:pkg:fun:err` e.g. `signals:sig:keepWhen:notEnoughInputs`. Or perhaps without the module.
1. We could have a list of them on out readthedocs but I'm not sure that's worth it.
2. In Python people put an error list in their docstrings which might be a nice idea.  e.g.
```
Errors:
  Rigbox:exp:InferParameters:ReservedParameters - Parameter name reserved.  Rename parameter in your def function.
```

Here's MATLAB's suggestion for using identifiers: https://uk.mathworks.com/help/matlab/matlab_prog/capture-information-about-errors.html#bq9tdlq-1

Thoughts @jaib1?

**Comment by jaib1** [comment]
Sure, I'm fine with your '0' suggestion. We could do all 3, but at least '0' is a nice start. We should have this documented somewhere.
