### ISSUE TITLE
typo/bug: gamma correction doesn't work

### ISSUE THREAD

**Issue by petersaj** [cortex-lab/Rigbox#216]
srv.expServer Line 368: turns off plotting the figure

hw.ptb.Window Line 712: uses the variable "upCrossings" which is only generated by line 688 if the figure plot is turned on

so as it's written gamma correction can't happen - this issue is fixed by generating the up/downcrossings outside of the figure-related code

**Comment by k1o0** [comment]
Cheers for the info! Mind making a PR?

**Comment by petersaj** [comment]
I've never done a pull request before - I thought that might happen if I attempted to push to master but it ended up just committing the code. Not sure if I should just leave it?

**Comment by k1o0** [comment]
Pushed already by Andy (7d6b6010d9166632ba5a7181ed9414ea866480f7)
