### ISSUE TITLE
save signals 'events' field when a signals experiment ends on error

### ISSUE THREAD

**Issue by jaib1** [cortex-lab/Rigbox#218]
maybe add exception handling to `exp.SignalsExp/mainLoop` ?

**Comment by k1o0** [comment]
This is already the case.  Perhaps you could replicate the problem?  If not then please close the issue.

**Comment by jaib1** [comment]
No, this has happened to both Tim and Anna this past week due to errors updating signals in their exp defs during runtime. I'll look more into possible solutions
