### ISSUE TITLE
Merge SignalsPrimer and GettingStartedWithSignals

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/Rigbox#234]
The latter demonstrates almost exactly the same stuff but in less detail.  These two should be merged.  Ideally there should be 2 tutorials, one on using signals outside of the experiment framework, and one within.

**Comment by jaib1** [comment]
> Ideally there should be 2 tutorials, one on using signals outside of the experiment framework, and one within.

Yes, I would say two _sets_ of tutorials. This is what I had in mind with `GettingStartedWithSignals` and `SignalsExpDefTutorial`. 

Merging is a good idea. I've received positive feedback on the questions and answers in `GettingStartedWithSignals` so I think this should be kept in the merge. Also, I think breaking both sets down into multiple scripts (one "part" per script) is helpful - I think it avoids people feeling overwhelmed, and gives them intermittent reward when finishing a part.
