### ISSUE TITLE
Minimum water requirement in Alyx not consistent with google sheets

### ISSUE THREAD

**Issue by laurax452** [cortex-lab/Rigbox#24]
Water requirement in Alxy is different from the minimum water requirement currently in google sheets for most/all(?) animals. Can't see where discrepancy lies.

**Comment by nsteinme** [comment]
Thanks, @k1o0 could you investigate? First check implant weight, ref weight, age, gender all match for some mouse. Then whether z-score matches, which will help determine what part of algorithm diverges.

**Comment by laurax452** [comment]
Miles and I checked the things like implant weight, age, z score and gender for a couple of mice- e.g. Vin, Diesel, Kendall.
They all matched – I haven’t checked for all mice but essentially I think they all match.
Alk041 has a z score that doesn’t match, there may be more examples of this.

**Comment by nsteinme** [comment]
Ok, great. This is an alyx issue so I'm going to move it there.

**Comment by k1o0** [comment]
I haven't updated the code yet so let's hold off until tomorrow
