### ISSUE TITLE
include git commit hashes in parameters struct

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/Rigbox#37]
For timeline.hw, also for block/experiment.
How to extract them from relevant repositories?

**Comment by mkrumin** [comment]
if you have git installed, and runnable from cmd/powershell

[s, hash] = system('git rev-parse HEAD')

**Comment by nsteinme** [comment]
Awesome, thanks for that. Note to self or @k1o0 :
`[s, hash] = system(sprintf('git -C "%s" rev-parse HEAD', fileparts(which('funcName'))))
`
where funcName is a function in the root of the repository, like "mc" for Rigbox, or "addSignalsPaths" for signals.

**Comment by k1o0** [comment]
The parameters struct is saved by mc, not expServer, and we want to know what code the stimulus computer is running.  Loading the file and re-saving is not ideal...

**Comment by nsteinme** [comment]
Good point - we don't really want it with the parameters struct anyway - we want it with the hardware info: #40 

My mistake, but I still think it's a good idea to have in this other location.

**Comment by k1o0** [comment]
a27c33aeb488f58dabd8a4a7897e61802a51ac28
