### ISSUE TITLE
Timeline class output objects

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/Rigbox#38]
I think a few changes should be made to the timeline output objects:

1. In accordance with good programming practice the class names and property names should start with a capital letter.  The point of this is that it reduces confusion between methods, properties and classes when using the dot notation.
2. TLOutputAcqLive should be modified to fulfill the purpose of tlOutputStartStop as both signal acquisition state to other instruments and both are currently very small classes.
3. TLOutputAcqLive should output a low by default when the stop method is called
4. The Session and ClockChan properties are unprotected and not hidden.  Shouldn't everything that interacts with the DAQ objects be in the TLOutput methods?   
5. If you can think of some better, more informative names for these classes and timeline properties in general, now would be the time to change them!

I'm sorry I didn't raise these issues earlier before the merge but I didn't have the time until today to properly look over everything.  I've already made most of these changes (and a few other minor ones) locally.  Ideally we can resolve everything before Friday, when tl-as-class is set to be merged with the master branch.  I can reload the timeline class on all the other rigs if you do Kilotrode.  First I will push these changes to tl-as-class_outputClasses.

**Comment by nsteinme** [comment]
Let me know what branch you have with some of these changes?
