### ISSUE TITLE
save copy of hardware.mat with each experiment

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/Rigbox#40]
We maybe want to check that no one's hardware.mat is too big (I think Pip's are, and we should fix that, I'm sure it's an accident), but then we should really save a copy of this with every experiment. If something gets changed there's no way to tell currently which one you actually used to run the experiment. It can happen from expServer, at the same time the Block file is saved. @k1o0 thoughts?

**Comment by nsteinme** [comment]
Steps:
1) Fix Pip's audio calibration hardware.mats
2) Copy hardware.mat directly into save directory
3) implement saving as json for better interoperability

**Comment by k1o0** [comment]
590c17bb707a06b008468a1881e2ae90b61018ec
