### ISSUE TITLE
suggestion: update parameters during experiment

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/Rigbox#57]
Idea: if you open up the parameters box from the exp panel and change something, it can send a message back to signals that posts these new parameters values. Would have to also update the allCondPars, etc.

**Comment by k1o0** [comment]
This can now be done in the `eui.SignalsTest` GUI.
https://github.com/cortex-lab/Rigbox/blob/e073ed6f8ec3f78b7f75d67344769454b9e39195/%2Bexp/%2Btest/Signals.m#L14-L28
62eb9ac7f927daf95104a00194eb00aab2d33f73
