### ISSUE TITLE
Running signals and ChiceWorld on the same rig at the same time

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/Rigbox#6]
Currently it's possible to start a ChoiceWorld experiment over the top of an already running signals one.  One of the start button call-backs needs tweaking

**Comment by k1o0** [comment]
I've implemented a fix for this, soon to be tested

**Comment by nsteinme** [comment]
I believe instead you broke experiment launching! Peter currently can't
start an experiment in the training room.
