### ISSUE TITLE
ExpPanel tab should accomodate more experiments

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/Rigbox#80]
Related to #72: Let's create a better experiment panel tab to accommodate more experiments running in parallel.  For instance a way to shrink panels down or choose between compact and full views.  This is necessary as soon there will be many more people running experiments in the training room.

**Comment by nsteinme** [comment]
Easier solution: get a second monitor.

**Comment by k1o0** [comment]
We're going to be very tight for space in the training room: there will be 11 rigs, three of which will need an external monitor of there own.  For the blue training rigs there's already 2 monitors because one is for the inactivations.  The desk for the reg rigs is going to be a lot smaller.  I'm glad I won't be training in that room any longer :)

**Comment by nsteinme** [comment]
https://www.scan.co.uk/products/ergotron-ds100-quad-monitor-stand-horizontal

**Comment by k1o0** [comment]
Yeah we'll certainly need extra monitors, regardless.  Goodbye, lovely window view!

**Comment by k1o0** [comment]
Hiding tabs is probably not something we need to incorporate; instead being able to re-instantiate a panel for a running experiment would help (#79) and now individual event labels can be hidden, helping the vertical aspect (4ff4d0f).  Closing for now.
