### ISSUE TITLE
Git.update fails if there have not been any updates

### ISSUE THREAD

**Issue by jjlee42** [cortex-lab/Rigbox#94]
When I try to run mc (for the first time) I am getting this error:

```
Insufficient number of outputs from right hand side of equal sign to satisfy assignment.

Error in getOr (line 20)
    v = s.(field);

Error in git.update (line 12)
lastFetch = getOr(dir(fullfile(root, '.git', 'FETCH_HEAD')), 'datenum');

Error in mc (line 9)
git.update();`c
```

Which is because `C:\Users\Experiment\Rigbox\.git\FETCH_HEAD` does not exist.

I suspect this is because I have only ever cloned the repo and have never done a "git pull" which I guess would populate the file it is looking for. "git pull" doesn't work (because it is up to date). How do I work around this?

**Comment by k1o0** [comment]
Fix'd 7ad3bab93386a26c83cbd9b4757eedbf09b96a8c
