### ISSUE TITLE
exp.inferParameters error when trying to create a non-scalar parameter for a 'vis' element

### ISSUE THREAD

**Issue by jaib1** [cortex-lab/Rigbox#99]
e.g. trying to do something in an Exp Def like this: 
`stim = vis.grating(t);`
`stim.contrast = params.Contrast;`
`params.Contrast = [0 0.25 0.5 0.75 1]`
throws

> Error using  .* 
Matrix dimensions must agree.

exp.inferParameters should handle this better.

**Comment by k1o0** [comment]
e47f4624469a9935d8c77e8372ad005447b6a597 for testing
